
* Compiling

We compile the pdel script into pdel assembly.
pdel assembly has also x y and so on.
After creating the elements with assembly,
then we call the layout function, that sets the x and y
and widths and so on.

After this we can create the pd file and


* Launching Pure Data from a form

A PDEL form can be assembled, laid out, written to a temporary =.pd= file,
and launched in Pure Data directly:

#+begin_src lisp
(pdel-pd:launch-form
 '(osc~ #(440)
   (mtofreq
    (midiin))))
#+end_src

The function returns three values: the UIOP process object, the generated
pathname, and the laid-out assembly.

#+begin_src lisp
(multiple-value-bind (process pathname assembly)
    (pdel-pd:launch-form
     '(osc~ #(440)
       (mtofreq
        (midiin))))
  (declare (ignore assembly))
  (format t "Pd process: ~S~%Patch: ~A~%" process pathname))
#+end_src

Use =:gui nil= for =pd -nogui=, =:pd= to select another executable, and
=:arguments= for extra Pure Data command-line arguments.




* Syntax

You can write anything that

(whatever ...) -> assembly

But I want to be able to define functions and macros


#+begin_src lisp
       (defpdel my-new-sketch
           :args (args..)
           :inputs (inputs..)
           :outputs (outputs..)
           :flags (flags...))
#+end_src

and this should add the thing to the objlist, but it should also create a common-lisp macro called

my-new-sketch

that when I call it, it should launch the pd sketch compiled,i.e.,

(my-new-osc~ nil (mtof (midiin) :flag1 t)

and so on.

* Special Pd records

PDEL distinguishes ordinary =#X obj= nodes from Pd records whose patch-file
syntax is different:

#+begin_src lisp
(msg "set 440")
(msg #("1 2, 0 250 2") (bang))
(text "a canvas comment")
(comment "alias for text")
(floatatom #(5 0 127 0 "" "" ""))
(symbolatom #(10 0 0 0 "" "" ""))
(listbox #(20 0 0 0 "" "" ""))
#+end_src

=msg=, =floatatom=, =symbolatom= and =listbox= are connectable assembly
elements. =text=/=comment= consume a canvas object index but are not treated as
connection sources. Structural records do not consume object IDs:

#+begin_src lisp
(declare -path "else")
(raw "#X coords 0 0 1 1 100 100 1;")
#+end_src

=declare= records are emitted before canvas elements. =raw= records are emitted
after normal elements and connections and are intended for structural Pd syntax,
not arbitrary connectable objects.

* Tests

Run the Common Lisp sanity suite with:

#+begin_src sh
./tests/run-tests.sh
#+end_src

The runner uses ASDF and SBCL and executes =asdf:test-system :pdel=.
